[DEFAULT]
# filepaths
database = data/adatok.db
waybillfolder = data/Szállítólevelek/
logfile = data/uberzeug.log
turnoverfolder = data/Forgalom/
stockfolder = data/Készlet/

# images, icons
title_image = data/titleimg.gif
windows_icon = data/pohlen.ico
linux_icon = data/pohlen.gif

# data
lookback_days = 60